---
site_name: EuXFEL Software Environments
site_description: European XFEL Software Environments
site_url: https://european-xfel.github.io/environments

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.jpeg
  palette:
    scheme: preference
    language: en
  features:
    - announce.dismiss
    - content.tabs.link
    - navigation.indexes # section index pages
    - navigation.top # back to top button
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

repo_url: https://github.com/European-XFEL/environments

extra_css:
  - stylesheets/extra.css

nav:
  - index.md
  - Using Environments: "environments.md"
  - What's Available:
      - Environment List: "environments/"
      - Module List: "modules/"
      - Recipe List: "recipes/"
  - Maintenance:
      - Environment Management: "maintenance/environments.md"
      - Recipe Creation: "maintenance/recipes.md"
      - Conda Installations: "maintenance/instances.md"

plugins:
  - search
  - literate-nav
  - gen-files:
      scripts:
        - ./docs/gen_environments.py
        - ./docs/gen_modules.py
        - ./docs/gen_recipes.py

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/European-XFEL
