name: "202401"
channels:
  - nodefaults
  - /gpfs/exfel/sw/software/euxfel-environment-management/custom-recipes/conda-bld
  - conda-forge
dependencies:
  - python=3.10
  - brotlipy=0.7.0
  - certipy=0.1.3
  - ipykernel=6.13.1
  - ipympl=0.9.3
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jupyter=1.0.0
  - jupyter-server-mathjax=0.2.6
  - jupyter-server-proxy=4.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyter_telemetry=0.1.0
  - jupyterhub=2.3.1
  - jupyterhub-base=2.3.1
  - jupyterlab=3.4.3
  - jupyterlab-git=0.41.0
  - jupyterlab-h5web=7.0.0
  - jupyterlab_code_formatter=1.6.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - jupyterlab_widgets=1.1.0
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - pyls-spyder=0.4.0
  - scipy=1.8.1
  - spyder=5.3.1
  - spyder-kernels=2.3.1
  - cpuonly::pytorch
  - pytorch::pytorch
  - torchaudio::pytorch
  - torchvision::pytorch
  - astropy
  - bokeh
  - curl
  - cython
  - dask
  - dask-jobqueue
  - dask-labextension
  - fabio
  - fast-histogram
  - fftw
  - h5glance>=0.8.1
  - h5netcdf
  - h5py
  - imageio
  - iminuit
  - jupyterlab-lsp
  - kafka-python
  - lmfit
  - mpl-interactions
  - msgpack-numpy
  - msgpack-python
  - natsort
  - netcdf4
  - numba
  - numpy
  - opencv
  - papermill
  - plotly
  - polars
  - pybaselines
  - pyfai
  - pyopengl
  - pyqtgraph
  - pytest
  - pywavelets
  - pyzmq<25
  - scikit-beam
  - scikit-image
  - scikit-learn
  - seaborn
  - silx
  - xarray
  - xraylib
  - calibration-client >=11.3.0
  - cfelpyutils
  - condat-gridconv
  - envmodules
  - euxfel-bunch-pattern
  - extra-data >= 1.14
  - extra-geom
  - extra-hed
  - findxfel
  - hdf5-vds-check
  - karabo-bridge
  - karabo_bridge_recorder
  - matplotlib-scalebar
  - metadata-client
  - metropc
  - nbclick
  - pasha
  - princess
  - condor
